name: Build and test
description: Installs dependencies, builds, and runs tests

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19
        registry-url: "https://registry.npmjs.org"

    - name: Set up pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install, build, and test
      run: pnpm it
      shell: bash
